@extends('layouts.app')
@section('title','MixHome — Controle de Home Office')
@section('content')
<main><section id="employee" class="view workspace">
  <div class="hero"><div><p class="eyebrow">CONTROLE DE PRESENÇA</p><h1>Olá, {{ explode(' ',trim(auth()->user()->name))[0] }}.<br>Solicite seu <em>home office.</em></h1><p>Marque no calendário os dias e envie para aprovação do gestor.</p></div><div class="counter"><strong id="selectedCount">0</strong><span>DIAS SELECIONADOS</span></div></div>
  <div class="layout">
    <article class="card identity"><div class="title"><span>01</span><h2>Seu perfil</h2></div><div class="profile-data"><small>NOME</small><b>{{ auth()->user()->name }}</b><small>E-MAIL</small><span>{{ auth()->user()->email }}</span><small>EQUIPE</small><span>{{ auth()->user()->team ?: 'Não informada' }}</span></div><form method="post" action="{{ route('logout') }}">@csrf<button class="change-profile text-action">Trocar usuário</button></form><p class="safe">✓ Suas solicitações serão vinculadas a este perfil.</p></article>
    <article class="card calendar-card"><div class="calendar-head"><div class="title"><span>02</span><h2>Selecione os dias</h2></div><div class="month-nav"><button id="prevMonth" aria-label="Exibir mês anterior">←</button><b id="monthLabel" aria-live="polite"></b><button id="nextMonth" aria-label="Exibir próximo mês">→</button></div></div><div class="calendar-legend" aria-label="Legenda do calendário"><span><i class="legend-pending"></i>Pendente</span><span><i class="legend-approved"></i>Aprovada</span><span><i class="legend-rejected"></i>Recusada</span><span><i class="legend-national"></i>Nacional</span><span><i class="legend-state"></i>Estadual</span><span><i class="legend-manual"></i>Corporativa</span></div><div class="week" aria-hidden="true"><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span><span>DOM</span></div><div id="calendar" class="calendar" role="grid" aria-label="Calendário para solicitação de home office"></div><div class="action"><p id="notice" role="status" aria-live="polite">Revise as datas antes de enviar.</p><button id="register" class="primary">Enviar solicitação <span>→</span></button></div></article>
  </div>
  @if($notifications->isNotEmpty())<article class="card employee-notifications"><div class="history-head"><div><p class="eyebrow">ATUALIZAÇÕES</p><h2>Notificações recentes</h2></div></div><div class="notification-list">@foreach($notifications as $notification)@php($isVacation=($notification->data['type']??'')==='vacation_status')<div><b>{{ $isVacation ? 'Férias '.(['approved'=>'aprovadas','rejected'=>'recusadas','cancelled'=>'canceladas'][$notification->data['status']??'']??'atualizadas') : (($notification->data['type'] ?? '')==='pending_digest' ? ($notification->data['count'].' pendências aguardando análise') : (($notification->data['status'] ?? '')==='approved'?'Solicitação aprovada':(($notification->data['status'] ?? '')==='rejected'?'Solicitação recusada':'Solicitação atualizada'))) }}</b><span>{{ $isVacation ? \Carbon\Carbon::parse($notification->data['starts_on'])->format('d/m/Y').' a '.\Carbon\Carbon::parse($notification->data['ends_on'])->format('d/m/Y') : (isset($notification->data['date']) ? \Carbon\Carbon::parse($notification->data['date'])->format('d/m/Y') : 'Consulte o painel de gestão') }}</span><small>{{ $notification->created_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }}</small></div>@endforeach</div></article>@endif
  <article class="card employee-history"><div class="history-head"><div><p class="eyebrow">MEU HISTÓRICO</p><h2>Dias já registrados</h2></div><div class="history-total"><strong>{{ $records->total() }}</strong><span>REGISTROS</span></div></div><p class="readonly-note">🔒 Solicitações enviadas não podem ser alteradas. Acompanhe abaixo a análise do gestor.</p>
    @if($records->isEmpty())<p class="empty compact-empty">Você ainda não possui dias registrados.</p>@else<div class="history-grid">@foreach($records as $record)<div class="history-item status-{{ $record->status }}"><div class="date-badge"><strong>{{ $record->work_date->format('d') }}</strong><span>{{ strtoupper($record->work_date->locale('pt_BR')->translatedFormat('M')) }}</span></div><div><b>{{ $record->work_date->format('d/m/Y') }}</b><small>{{ $record->work_date->locale('pt_BR')->translatedFormat('l') }}</small><span class="request-timeline"><i class="done"></i> Enviada {{ $record->created_at->timezone(config('app.timezone'))->format('d/m H:i') }} <i class="{{ $record->reviewed_at?'done':'' }}"></i> {{ $record->reviewed_at ? ucfirst(['approved'=>'aprovada','rejected'=>'recusada'][$record->status] ?? 'analisada').' por '.($record->reviewer?->name ?? 'gestor').' em '.$record->reviewed_at->timezone(config('app.timezone'))->format('d/m H:i') : 'Aguardando análise' }}</span>@if($record->review_note)<span class="review-note"><b>Observação do gestor:</b> {{ $record->review_note }}</span>@endif</div><span class="request-status">{{ ['pending'=>'Pendente','approved'=>'Aprovada','rejected'=>'Recusada'][$record->status] ?? 'Pendente' }}</span></div>@endforeach</div><div class="directory-pagination">{{ $records->links() }}</div>@endif
  </article>
</section></main>
@endsection
@push('scripts')<script>window.HIBRIDO_REQUEST_URL=@json(route('employee.requests.store'));window.HIBRIDO_CSRF=@json(csrf_token());window.HIBRIDO_HOLIDAYS={{ Illuminate\Support\Js::from($holidays->map(fn($holiday) => ['date' => $holiday->date->format('Y-m-d'), 'name' => $holiday->name, 'blocked' => $holiday->blocks_requests, 'scope' => $holiday->scope, 'source' => $holiday->source])->values()) }};window.HIBRIDO_REQUESTS={{ Illuminate\Support\Js::from($calendarRequests->map(fn($record) => ['date' => $record->work_date->format('Y-m-d'), 'status' => $record->status])->values()) }};</script><script src="{{ asset('assets/app.js') }}?v={{ filemtime(public_path('assets/app.js')) }}" defer></script>@endpush
