@extends('layouts.app')
@section('title','Híbrido — Controle de Home Office')
@section('content')
<main><section id="employee" class="view workspace">
  <div class="hero"><div><p class="eyebrow">CONTROLE DE PRESENÇA</p><h1>Olá, {{ explode(' ',trim(auth()->user()->name))[0] }}.<br>Solicite seu <em>home office.</em></h1><p>Marque no calendário os dias e envie para aprovação do gestor.</p></div><div class="counter"><strong id="selectedCount">0</strong><span>DIAS SELECIONADOS</span></div></div>
  <div class="layout">
    <article class="card identity"><div class="title"><span>01</span><h2>Seu perfil</h2></div><div class="profile-data"><small>NOME</small><b>{{ auth()->user()->name }}</b><small>E-MAIL</small><span>{{ auth()->user()->email }}</span><small>EQUIPE</small><span>{{ auth()->user()->team ?: 'Não informada' }}</span></div><form method="post" action="{{ route('logout') }}">@csrf<button class="change-profile text-action">Trocar usuário</button></form><p class="safe">✓ Suas solicitações serão vinculadas a este perfil.</p></article>
    <article class="card calendar-card"><div class="calendar-head"><div class="title"><span>02</span><h2>Selecione os dias</h2></div><div class="month-nav"><button id="prevMonth" aria-label="Mês anterior">←</button><b id="monthLabel"></b><button id="nextMonth" aria-label="Próximo mês">→</button></div></div><div class="week"><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span><span>DOM</span></div><div id="calendar" class="calendar"></div><div class="action"><p id="notice">Revise as datas antes de enviar.</p><button id="register" class="primary">Enviar solicitação <span>→</span></button></div></article>
  </div>
  <article class="card employee-history"><div class="history-head"><div><p class="eyebrow">MEU HISTÓRICO</p><h2>Dias já registrados</h2></div><div class="history-total"><strong>{{ $records->count() }}</strong><span>REGISTROS</span></div></div><p class="readonly-note">🔒 Solicitações enviadas não podem ser alteradas. Acompanhe abaixo a análise do gestor.</p>
    @if($records->isEmpty())<p class="empty compact-empty">Você ainda não possui dias registrados.</p>@else<div class="history-grid">@foreach($records as $record)<div class="history-item status-{{ $record->status }}" title="Enviado em {{ $record->created_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }}"><div class="date-badge"><strong>{{ $record->work_date->format('d') }}</strong><span>{{ strtoupper($record->work_date->locale('pt_BR')->translatedFormat('M')) }}</span></div><div><b>{{ $record->work_date->format('d/m/Y') }}</b><small>{{ $record->work_date->locale('pt_BR')->translatedFormat('l') }}</small></div><span class="request-status">{{ ['pending'=>'Pendente','approved'=>'Aprovada','rejected'=>'Recusada'][$record->status] ?? 'Pendente' }}</span></div>@endforeach</div>@endif
  </article>
</section></main>
@endsection
@push('scripts')<script>window.HIBRIDO_REQUEST_URL=@json(route('employee.requests.store'));window.HIBRIDO_CSRF=@json(csrf_token());</script><script src="{{ asset('assets/app.js') }}?v={{ filemtime(public_path('assets/app.js')) }}" defer></script>@endpush
