@extends('layouts.app')
@section('title','Gestão de férias — MixHome')
@section('bodyClass','manager-page')
@section('content')
<main><section class="workspace manager-workspace vacation-workspace">
  <div class="manager-head"><div><p class="eyebrow">PAINEL DO GESTOR</p><h1>Planejamento de <em>férias.</em></h1><p>Analise solicitações e acompanhe a disponibilidade das equipes.</p></div><a class="primary button-link" href="{{ route('manager.vacations.export',request()->query()) }}">Exportar CSV ↓</a></div>
  <nav class="manager-sections"><a href="{{ route('manager.dashboard') }}">Home office</a><a class="active" href="{{ route('manager.vacations.index') }}">Férias</a></nav>
  <article class="card filters-card"><form class="filters vacation-filters"><label>Nome ou e-mail<input name="q" value="{{ request('q') }}" placeholder="Pesquisar colaborador"></label><label>Equipe<select name="team"><option value="">Todas permitidas</option>@foreach($teams as $team)<option @selected(request('team')===$team)>{{ $team }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">Todos</option>@foreach(['pending'=>'Pendentes','approved'=>'Aprovadas','rejected'=>'Recusadas','cancelled'=>'Canceladas'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></label><button class="primary">Aplicar filtros</button></form></article>
  <article class="card vacation-calendar"><div class="report-head"><div><p class="eyebrow">CALENDÁRIO DA EQUIPE</p><h2>Próximas férias aprovadas</h2></div></div><div class="vacation-team-grid">@forelse($approved as $item)<div><b>{{ $item->user->name }}</b><span>{{ $item->user->team }}</span><time>{{ $item->starts_on->format('d/m/Y') }} → {{ $item->ends_on->format('d/m/Y') }}</time></div>@empty<p class="empty">Nenhuma férias aprovada futura.</p>@endforelse</div></article>
  <article class="card report"><div class="report-head"><div><p class="eyebrow">SOLICITAÇÕES</p><h2>{{ $vacations->total() }} resultados</h2></div></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Equipe</th><th>Período</th><th>Dias</th><th>Status</th><th>Ações</th></tr></thead><tbody>@forelse($vacations as $vacation)<tr><td><b>{{ $vacation->user->name }}</b><small>{{ $vacation->user->email }}</small></td><td>{{ $vacation->user->team }}</td><td>{{ $vacation->starts_on->format('d/m/Y') }} → {{ $vacation->ends_on->format('d/m/Y') }}</td><td>{{ $vacation->starts_on->diffInDays($vacation->ends_on)+1 }}</td><td><span class="request-badge">{{ ['pending'=>'Pendente','approved'=>'Aprovada','rejected'=>'Recusada','cancelled'=>'Cancelada'][$vacation->status] }}</span></td><td class="review-actions">@if($vacation->status==='pending')<form method="post" action="{{ route('manager.vacations.review',$vacation) }}" class="vacation-review">@csrf<input name="review_note" maxlength="1000" placeholder="Observação opcional"><button name="decision" value="approved" class="approve-action">Aprovar</button><button name="decision" value="rejected" class="reject-action">Recusar</button></form>@endif @if(auth()->user()->role==='super_admin' && $vacation->status!=='cancelled')<details class="request-menu"><summary>Administrar</summary><div class="request-menu-panel"><form method="post" action="{{ route('admin.vacations.correct',$vacation) }}">@csrf @method('PUT')<input type="date" name="starts_on" value="{{ $vacation->starts_on->format('Y-m-d') }}" required><input type="date" name="ends_on" value="{{ $vacation->ends_on->format('Y-m-d') }}" required><textarea name="note" required placeholder="Justificativa da correção"></textarea><button class="secondary">Corrigir</button></form><form method="post" action="{{ route('admin.vacations.cancel',$vacation) }}">@csrf<input name="note" required placeholder="Justificativa do cancelamento"><button class="reject-action">Cancelar</button></form></div></details>@endif</td></tr>@empty<tr><td colspan="6" class="empty">Nenhuma solicitação encontrada.</td></tr>@endforelse</tbody></table></div>{{ $vacations->links() }}</article>
</section></main>
@endsection
