@extends('layouts.app')
@section('title','Gestão de férias — MixHome')
@section('bodyClass','manager-page')
@section('content')
<main><section class="workspace manager-workspace vacation-workspace">
  <div class="manager-head"><div><p class="eyebrow">PAINEL DO GESTOR</p><h1>Planejamento de <em>férias.</em></h1><p>Analise solicitações e acompanhe a disponibilidade das equipes.</p></div><a class="primary button-link" href="{{ route('manager.vacations.export',request()->query()) }}">Exportar CSV ↓</a></div>
  @include('manager._navigation')
  @if(auth()->user()->role==='super_admin')
  <article class="card vacation-entitlement-admin">
    <div class="balance-simple-head"><div><p class="eyebrow">SALDOS DE FÉRIAS</p><h2>Controle automático</h2><p>Você só precisa manter a data de admissão correta. O MixHome calcula o saldo.</p></div><a class="primary button-link" href="{{ route('admin.users.index') }}">Informar admissões →</a></div>
    <div class="balance-steps"><span><b>1</b> Abra Usuários</span><span><b>2</b> Informe a admissão</span><span><b>3</b> O saldo aparece aqui</span></div>
    <div class="entitlement-list"><h3>Períodos e saldos</h3>@forelse($entitlements as $entitlement)<details><summary><b>{{ $entitlement->user->name }}</b><span>{{ $entitlement->acquisition_starts_on->format('d/m/Y') }} → {{ $entitlement->acquisition_ends_on->format('d/m/Y') }}</span>@if($entitlement->isAccruing())<strong class="entitlement-state state-accruing">Em formação · libera {{ $entitlement->acquisition_ends_on->copy()->addDay()->format('d/m/Y') }}</strong>@elseif($entitlement->isExpired())<strong class="entitlement-state state-expired">Vencido em {{ $entitlement->expires_on->format('d/m/Y') }}</strong>@else<strong class="entitlement-state state-available">{{ $entitlement->availableDays() }} disponíveis</strong>@endif</summary><form method="post" action="{{ route('admin.vacation-entitlements.update',$entitlement) }}" class="entitlement-form compact">@csrf @method('PUT')<label>Prazo para uso<input type="date" name="expires_on" value="{{ $entitlement->expires_on?->format('Y-m-d') }}"></label><label>Concedidos<input type="number" name="granted_days" value="{{ $entitlement->granted_days }}" min="0" max="90" required></label><label>Ajuste<input type="number" name="adjustment_days" value="{{ $entitlement->adjustment_days }}" min="-90" max="90" required></label><label class="entitlement-note">Motivo do ajuste<textarea name="notes" maxlength="1000" required>{{ $entitlement->notes }}</textarea></label><button class="secondary">Salvar ajuste</button><p>{{ $entitlement->approvedDays() }} utilizados · {{ $entitlement->reservedDays() }} reservados · {{ $entitlement->totalDays() }} concedidos</p></form></details>@empty<p class="empty">Nenhum período calculado ainda.</p>@endforelse</div>
    <details class="advanced-balance"><summary>Opções avançadas do RH</summary><p>Use somente para cadastrar uma exceção que não possa ser gerada pela data de admissão.</p><form method="post" action="{{ route('admin.vacation-entitlements.store') }}" class="entitlement-form">@csrf
      <label>Colaborador<select name="user_id" required><option value="">Selecionar</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} — {{ $employee->email }}</option>@endforeach</select></label>
      <label>Início aquisitivo<input type="date" name="acquisition_starts_on" required></label><label>Fim aquisitivo<input type="date" name="acquisition_ends_on" required></label><label>Prazo para uso<input type="date" name="expires_on"></label><label>Dias concedidos<input type="number" name="granted_days" min="0" max="90" value="30" required></label><label>Ajuste<input type="number" name="adjustment_days" min="-90" max="90" value="0"></label><label class="entitlement-note">Justificativa<textarea name="notes" maxlength="1000" required></textarea></label><button class="primary">Cadastrar exceção</button>
    </form></details>
  </article>
  @endif
  <article class="card filters-card"><form class="filters vacation-filters"><label>Nome ou e-mail<input name="q" value="{{ request('q') }}" placeholder="Pesquisar colaborador"></label><label>Equipe<select name="team"><option value="">Todas permitidas</option>@foreach($teams as $team)<option @selected(request('team')===$team)>{{ $team }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">Todos</option>@foreach(['pending'=>'Pendentes','approved'=>'Aprovadas','rejected'=>'Recusadas','cancelled'=>'Canceladas'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></label><button class="primary">Aplicar filtros</button></form></article>
  <article class="card vacation-calendar"><div class="report-head"><div><p class="eyebrow">CALENDÁRIO DA EQUIPE</p><h2>Próximas férias aprovadas</h2></div></div><div class="vacation-team-grid">@forelse($approved as $item)<div><b>{{ $item->user->name }}</b><span>{{ $item->user->team }}</span><time>{{ $item->starts_on->format('d/m/Y') }} → {{ $item->ends_on->format('d/m/Y') }}</time></div>@empty<p class="empty">Nenhuma férias aprovada futura.</p>@endforelse</div></article>
  <article class="card report"><div class="report-head"><div><p class="eyebrow">SOLICITAÇÕES</p><h2>{{ $vacations->total() }} resultados</h2></div></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Equipe</th><th>Período</th><th>Dias / saldo</th><th>Status</th><th>Ações</th></tr></thead><tbody>
  @forelse($vacations as $vacation)<tr><td><b>{{ $vacation->user->name }}</b><small>{{ $vacation->user->email }}</small></td><td>{{ $vacation->user->team }}</td><td>@if($vacation->isAllowanceOnly())<b>Somente abono</b>@else{{ $vacation->starts_on->format('d/m/Y') }} → {{ $vacation->ends_on->format('d/m/Y') }}@endif @if($vacation->entitlement)<small>Aquisitivo: {{ $vacation->entitlement->acquisition_starts_on->format('d/m/Y') }} a {{ $vacation->entitlement->acquisition_ends_on->format('d/m/Y') }}</small>@endif</td><td><b>@if($vacation->isAllowanceOnly()){{ $vacation->cash_allowance_days }} abono@else{{ $vacation->days() }} descanso{{ $vacation->cash_allowance_days ? ' + '.$vacation->cash_allowance_days.' abono' : '' }}@endif</b>@if($vacation->entitlement)<small>{{ $vacation->entitlement->availableDays() }} ainda disponíveis</small>@else<small>Saldo legado não vinculado</small>@endif</td><td><span class="request-badge">{{ ['pending'=>'Pendente','approved'=>'Aprovada','rejected'=>'Recusada','cancelled'=>'Cancelada'][$vacation->status] }}</span></td><td class="review-actions">
    @if($vacation->status==='pending')<form method="post" action="{{ route('manager.vacations.review',$vacation) }}" class="vacation-review">@csrf<input name="review_note" maxlength="1000" placeholder="Observação opcional"><button name="decision" value="approved" class="approve-action">Aprovar</button><button name="decision" value="rejected" class="reject-action">Recusar</button></form>@endif
    @if(auth()->user()->role==='super_admin' && $vacation->status!=='cancelled')<details class="request-menu"><summary>Administrar</summary><div class="request-menu-panel vacation-admin-panel">
      @unless($vacation->isAllowanceOnly())<form method="post" action="{{ route('admin.vacations.correct',$vacation) }}" class="vacation-correction-form">@csrf @method('PUT')
        <header><strong>Corrigir solicitação</strong><small>Atualize o saldo ou o período mediante justificativa.</small></header>
        <label class="vacation-admin-balance"><span>Período aquisitivo</span><select name="vacation_entitlement_id" required><option value="">Selecionar período</option>@foreach($vacation->user->vacationEntitlements as $balance)<option value="{{ $balance->id }}" @selected($vacation->vacation_entitlement_id===$balance->id)>{{ $balance->acquisition_starts_on->format('d/m/Y') }} a {{ $balance->acquisition_ends_on->format('d/m/Y') }} — {{ $balance->availableDays($vacation->id) }} dias</option>@endforeach</select></label>
        <label><span>Início</span><input type="date" name="starts_on" value="{{ $vacation->starts_on->format('Y-m-d') }}" required></label>
        <label><span>Fim</span><input type="date" name="ends_on" value="{{ $vacation->ends_on->format('Y-m-d') }}" required></label>
        <label class="vacation-admin-note"><span>Justificativa da correção</span><textarea name="note" required placeholder="Descreva o motivo da alteração"></textarea></label>
        <button class="secondary">Salvar correção</button>
      </form>@endunless
      <form method="post" action="{{ route('admin.vacations.cancel',$vacation) }}" class="vacation-cancel-form">@csrf<label><span>Cancelar solicitação</span><input name="note" required placeholder="Informe o motivo do cancelamento"></label><button class="reject-action">Cancelar</button></form>
    </div></details>@endif
  </td></tr>@empty<tr><td colspan="6" class="empty">Nenhuma solicitação encontrada.</td></tr>@endforelse
  </tbody></table></div>@include('components.pagination', ['paginator' => $vacations])</article>
</section></main>
@endsection
@push('scripts')<script src="{{ asset('assets/manager.js') }}?v={{ filemtime(public_path('assets/manager.js')) }}" defer></script>@endpush
