<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/svg+xml" href="{{ asset('assets/favicon.svg') }}?v={{ filemtime(public_path('assets/favicon.svg')) }}"><title>@yield('title','MixHome')</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&family=Playfair+Display:ital,wght@0,600;1,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('assets/style.css') }}?v={{ filemtime(public_path('assets/style.css')) }}"><link rel="stylesheet" href="{{ asset('assets/manager.css') }}?v={{ filemtime(public_path('assets/manager.css')) }}"><link rel="stylesheet" href="{{ asset('assets/login.css') }}?v={{ filemtime(public_path('assets/login.css')) }}"><link rel="stylesheet" href="{{ asset('assets/employee.css') }}?v={{ filemtime(public_path('assets/employee.css')) }}"><link rel="stylesheet" href="{{ asset('assets/brand-theme.css') }}?v={{ filemtime(public_path('assets/brand-theme.css')) }}"><link rel="stylesheet" href="{{ asset('assets/workflow.css') }}?v={{ filemtime(public_path('assets/workflow.css')) }}"><script src="{{ asset('assets/theme.js') }}?v={{ filemtime(public_path('assets/theme.js')) }}"></script></head>
<body class="@yield('bodyClass')"><header class="topbar"><a class="brand" href="{{ auth()->check() ? (auth()->user()->isManager()?route('manager.dashboard'):route('employee.dashboard')) : route('login') }}"><img src="{{ asset('assets/mix-fiscal-mark.png') }}" alt="Mix Fiscal"><span>MixHome</span></a>
<nav>@auth @if(auth()->user()->isManager())<div class="workspace-switch" aria-label="Alternar painel"><a class="{{ request()->routeIs('employee.*')?'active':'' }}" href="{{ route('employee.dashboard') }}"><span aria-hidden="true">⌂</span>Meu home office</a><a class="{{ request()->routeIs('manager.*')?'active':'' }}" href="{{ route('manager.dashboard') }}"><span aria-hidden="true">▦</span>Gestão</a>@if(auth()->user()->role==='super_admin')<a class="{{ request()->routeIs('admin.users.*')?'active':'' }}" href="{{ route('admin.users.index') }}"><span aria-hidden="true">◎</span>Usuários</a>@endif</div>@endif<span class="user-label">{{ auth()->user()->name }}</span><form method="post" action="{{ route('logout') }}">@csrf<button class="tab active">Sair</button></form>@else<span class="secure-label">● AMBIENTE SEGURO</span>@endauth</nav></header>
@if(session('success') || session('warning') || ($errors->any() && ! request()->routeIs('login')))
<div class="flash-stack" aria-label="Notificações">
@if(session('success'))<div class="flash-message flash-success" role="status" data-flash data-timeout="7000"><span class="flash-icon" aria-hidden="true">✓</span><span class="flash-content"><b>Tudo certo</b><small>{{ session('success') }}</small></span><button type="button" data-flash-close aria-label="Fechar notificação">×</button><i aria-hidden="true"></i></div>@endif
@if(session('warning'))<div class="flash-message flash-warning" role="status" data-flash data-timeout="9000"><span class="flash-icon" aria-hidden="true">!</span><span class="flash-content"><b>Atenção</b><small>{{ session('warning') }}</small></span><button type="button" data-flash-close aria-label="Fechar notificação">×</button><i aria-hidden="true"></i></div>@endif
@if($errors->any() && ! request()->routeIs('login'))<div class="flash-message flash-error" role="alert" data-flash><span class="flash-icon" aria-hidden="true">!</span><span class="flash-content"><b>Não foi possível concluir</b><small>{{ $errors->first() }}</small></span><button type="button" data-flash-close aria-label="Fechar notificação">×</button></div>@endif
</div>
@endif
@yield('content')<footer><span class="footer-brand"><img src="{{ asset('assets/mix-fiscal-logo.svg') }}" alt="Mix Fiscal"><b>MixHome</b></span><span>Controle simples. Trabalho flexível.</span></footer><script src="{{ asset('assets/notifications.js') }}?v={{ filemtime(public_path('assets/notifications.js')) }}" defer></script>@stack('scripts')</body></html>
