@extends('layouts.app')
@section('title','Entrar — MixHome') @section('bodyClass','unified-login')
@section('content')
<main class="login-shell"><section class="login-copy"><img class="institutional-logo" src="{{ asset('assets/mix-fiscal-logo.png') }}" alt="Mix Fiscal"><p class="eyebrow">CONTROLE DE HOME OFFICE</p><h1>Um só acesso.<br><em>Duas experiências.</em></h1><p>Cadastre-se como colaborador para manter seu histórico ou entre como gestor para acompanhar suas equipes.</p><div class="login-note"><b>MF</b><span>Após o envio, seus registros ficam disponíveis apenas para consulta e não podem ser alterados.</span></div></section>
<section class="card unified-card"><div class="role-tabs" role="tablist"><a class="{{ $profile!=='manager'?'active':'' }}" href="{{ route('login',['perfil'=>'employee']) }}">Sou colaborador</a><a class="{{ $profile==='manager'?'active':'' }}" href="{{ route('login',['perfil'=>'manager']) }}">Sou gestor</a></div>
@if($errors->any())<div class="auth-alert" role="alert" aria-live="assertive"><span aria-hidden="true">!</span><p><b>Não foi possível entrar</b><small>{{ $errors->first() }}</small></p></div>@endif
@if($profile==='manager')
  <div class="login-heading"><span class="role-icon">↗</span><div><p class="eyebrow">ACESSO RESTRITO</p><h2>Painel do gestor</h2></div></div><p class="form-intro">Entre com sua conta individual de gestor ou Super Admin.</p>
  <form method="post" action="{{ route('login') }}" class="unified-form">@csrf<input type="hidden" name="profile" value="manager"><label>E-mail<input name="email" type="email" value="{{ old('email') }}" autocomplete="email" autofocus required></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label>@if(config('auth.password_recovery_enabled'))<a class="auth-help" href="{{ route('password.request') }}">Esqueci minha senha</a>@endif<button class="primary">Entrar como gestor <span>→</span></button></form>
@else
  <div class="employee-auth-tabs"><a class="{{ $mode!=='register'?'active':'' }}" href="{{ route('login',['perfil'=>'employee']) }}">Já tenho cadastro</a><a class="{{ $mode==='register'?'active':'' }}" href="{{ route('login',['perfil'=>'employee','modo'=>'register']) }}">Primeiro acesso</a></div>
  @if($mode==='register')<div class="login-heading compact"><span class="role-icon">+</span><div><p class="eyebrow">PRIMEIRO ACESSO</p><h2>Crie sua conta</h2></div></div><form method="post" action="{{ route('register') }}" class="unified-form register-form">@csrf<label>Nome completo<input name="name" value="{{ old('name') }}" required></label><label>E-mail corporativo<input name="email" type="email" value="{{ old('email') }}" required></label><label>Equipe / área<select name="team" required><option value="">Selecione</option>@foreach($teams as $team)<option @selected(old('team')===$team->name)>{{ $team->name }}</option>@endforeach</select></label><div class="password-grid"><label>Senha<input name="password" type="password" minlength="8" required></label><label>Confirmar senha<input name="password_confirmation" type="password" minlength="8" required></label></div><button class="primary">Criar conta e continuar <span>→</span></button></form>
  @else<div class="login-heading compact"><span class="role-icon">H</span><div><p class="eyebrow">BEM-VINDO DE VOLTA</p><h2>Acesse sua conta</h2></div></div><form method="post" action="{{ route('login') }}" class="unified-form">@csrf<input type="hidden" name="profile" value="employee"><label>E-mail corporativo<input name="email" type="email" value="{{ old('email') }}" autocomplete="email" autofocus required></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label>@if(config('auth.password_recovery_enabled'))<a class="auth-help" href="{{ route('password.request') }}">Esqueci minha senha</a>@endif<button class="primary">Entrar na minha conta <span>→</span></button></form>@endif
@endif
</section></main>
@endsection
